version: '3'

services:
  api:
    container_name: crm-utp
    image: crm-utp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9043:9043
    restart: always
    volumes:
      - /root/certs:/tmp/certs